Serializer Refactoring
lyndonb-bq/tinkerpop pull request #5
Opened 2022-02-03 21:02 UTC by L0Lmaker

*Issue #, if available:*

https://bitquill.atlassian.net/browse/AN-1005

*Description of changes:*

Refactored Graph Binary Serializer.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-03 23:33 UTC, lyndonb-bq commented
Some ideas:
1. Remove reader/writer from graphBinarySerializer, have single codec or something.
2. Remove mime type, use constant that is above 'graphBinaryMimeType'
3. Remove getDataType call, replace with struct use
4. Add error check and return on readTypeValue buffer.ReadValue()
5. Rename things like `myListSerializer` to just listSerializer

2022-02-03 23:33 UTC, lyndonb-bq requested changes
Some ideas:

Remove reader/writer from graphBinarySerializer, have single codec or something.
Remove mime type, use constant that is above 'graphBinaryMimeType'
Remove getDataType call, replace with struct use
Add error check and return on readTypeValue buffer.ReadValue()
Rename things like myListSerializer to just listSerializer

2022-02-04 01:33 UTC, lyndonb-bq approved these changes
LGTM - good work Rithin.

2022-02-04 18:10 UTC, xiazcy approved these changes

2022-02-04 18:55 UTC, merged